POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "NodeJS"
}

###

GET http://localhost:3333/courses


###
GET http://localhost:3333/courses/8d333566-531e-4447-be0d-6b31693919e9

###
PUT http://localhost:3333/courses/8d333566-531e-4447-be0d-6b31693919e9
Content-Type: application/json

{
  "title": "Curso de TypeScript"
}

###

DELETE http://localhost:3333/courses/8d333566-531e-4447-be0d-6b31693919e9